[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = { version = "0.10", features = ["transport"] }

[dev-dependencies]
tempfile = "3"
