name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install just
        run: cargo install just --locked
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin --locked
      - name: Run fmt
        run: just fmt
      - name: Run clippy
        run: just lint
      - name: Build
        run: just build
      - name: Test
        run: just test
      - name: Coverage
        run: just coverage
